### ISSUE TITLE
Create user information page

### ISSUE THREAD

**Issue by Oksetorben** [ITU-BDSA2024-GROUP23/Chirp#105]
# Feature: User Information Page and Forget Me

## UI Updates:
- [x] In the navigation bar, between links to timelines and logout, add a new link labeled **"About me"**. This link should only appear when a user is authenticated.
- [x] The link should redirect to a new **user information page** where the following information is displayed for the authenticated user:
  - [x] Personal data such as name and email address.
  - [x] A list of users that the authenticated user is following.
  - [x] All cheeps posted by the authenticated user.

### Optional Feature:
- [x] Provide an option to **download all the user's personal information** (e.g., CSV, plain text) as a zipped archive. This should include the user’s personal data and cheeps.

## Forget Me Button:

On the **user information page**, implement a **Forget Me!** button, styled in red. When clicked, this button should initiate the following actions:

### Delete User Information:
- [x] This button will remove all personal data related to the user, such as name, email address, and follow relationships, from the application.

### Implementation Details:
- [x] Our book *ASP.NET Core in Action*,  section 12.4.4 (implement the "Forget me!" feature as an update operation)
- [x] Optionally implement actual deletion or anonymization of the user's data, except for the cheep content (cheeps will remain but anonymized).

### Logout:
- [x] After the user clicks the **Forget Me!** button, they will be logged out of the Chirp! application.

## Acceptance Criteria:
- [x] **"About me"** link appears in the navbar when a user is authenticated.
- [x] User information page shows personal details and a list of followed users and cheeps.
- [x] **Forget Me!** button on the user information page anonymizes or deletes personal data and logs the user out.

**Comment by victormemborg** [comment]
TODO:

- [ ] Maybe use a general _userInfo partial on AboutMe?
- [ ] Improve UI (navbar is floating around)
