### ISSUE TITLE
Find better way get path of database

### ISSUE THREAD

**Issue by Kanerix** [ITU-BDSA2024-GROUP23/Chirp#23]
This code is very ugly and can easily break:
https://github.com/ITU-BDSA2024-GROUP23/Chirp/blob/0cfcf4a935faa8aba267f5039b467f11e20a7230/src/Chirp.CLI/Program.cs#L9

**Comment by Anju023** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by victormemborg** [comment]
Make sure that the path works when running the tests (both end2end and unit tests) and the application.
