### ISSUE TITLE
Add tests for our new structure

### ISSUE THREAD

**Issue by victormemborg** [ITU-BDSA2024-GROUP23/Chirp#66]
As a developer I want to add tests in order to maintain stability across our project.

Acceptance criteria:

**Unit tests**
- [x] Write tests for Chirp.Core
- [x] Write tests for Chirp.Infrastructure repos (in-memory)
- [x] Write tests for Chirp.Infrastructure services

**Integration test**
- [x] Write integration tests for Chirp.Web

**E2E tests**
- [x] Playwright E2E tests
- [x] Update workflow to ensure browsers are installed

**Comment by Kanerix** [comment]
@victormemborg & @Oksetorben hvad er status med det sidste step?

**Comment by victormemborg** [comment]
> @victormemborg & @Oksetorben hvad er status med det sidste step?

status er at folk er gået i stå - vi mangler pænt mange test, både unit tests og integration test med playwright..

**Comment by victormemborg** [comment]
We only need proper integration testing now
