### ISSUE TITLE
Add GitHub authentication to our Chirp application

### ISSUE THREAD

**Issue by victormemborg** [ITU-BDSA2024-GROUP23/Chirp#70]
In order to allow users to Cheep from their own profile, we need to refactor our application to allow authentication.

Acceptance criteria:

- [x] Refactor UI with a navbar
- [x] Add a localhost GitHub oAuth app (http://localhost:5273/auth/github) callback URL
- [x] Add a GitHub oAuth app for our production server
- [x] Refactor Program.cs to enable GitHub oAuth

Needs refactoring:

- [x] Maybe a user should be created/checked if already exists when authenticated?
- [x] Change the parameters of the CreateCheep() method in order to create a cheep with an authorized user?
- [x] Change testing environment 
- [x] Refactor environment variables to follow conventions (UPPERCASE and with `_`)

**Comment by victormemborg** [comment]
@21Philip check lige de to manglende checkboxes - kunne godt bruge forslag til hvordan vi forbedrer createcheep metoden

**Comment by Kanerix** [comment]
@victormemborg du er nok den eneste der har de GitHub secrets. Du skal lige slette dem og oprette dem med rigtige naming conventions. Det er opdateret i pipeline og koden. Så kan du complete det step som jeg har addet

**Comment by victormemborg** [comment]
> @victormemborg du er nok den eneste der har de GitHub secrets. Du skal lige slette dem og oprette dem med rigtige naming conventions. Det er opdateret i pipeline og koden. Så kan du complete det step som jeg har addet

Til jer der ikke ved det, så ligger de inde på discord
